- cookie-banner-rules-list.json
Adding 74 new rules for:
salesforce.com, discord.com, reuters.com, booking.com, wsj.com, bloomberg.com, wix.com, businessinsider.com, 20min.ch, google.at, google.be, google.de, orf.at, abv.bg, dr.dk, google.it, google.pt, aktuality.sk, google.bg, jutarnji.hr, iltalehti.fi, orange.fr, google.gr, google.hu, google.nl, onet.pl, google.ro, google.rs, sme.sk, google.es, expressen.se, google.ca, nieuwsblad.be, vecernji.hr, tv2.dk, skroutz.gr, idokep.hu, emag.ro, kupujemprodajem.com, google.sk, marca.com, google.se, google.ch, bild.de, krone.at, 24sata.hr, google.dk, google.fi, origo.hu, interia.pl, olx.ro, bazos.sk, google.ie, google.co.uk, t-online.de, 24chasa.bg, ekstrabladet.dk, repubblica.it, independent.ie, dagbladet.no, google.pl, willhaben.at, blitz.bg, leboncoin.fr, ilmeteo.it, …
> QA cookie banner rule updates

- cookie-banner-rules-list.json
Adding 294 new rules for:
aktualne.cz, sport24.gr, corriere.it, tv2.no, elmundo.es, censor.net, olx.bg, dnevnik.hr, google.cz, olx.pt, rte.ie, b92.net, pravda.sk, blocket.se, heute.at, sportal.bg, google.hr, google.com.ua, fakti.bg, njuskalo.hr, google.no, plovdiv24.bg, gsis.gr, vodafone.com, cas.sk, nova.bg, nova.cz, op.fi, marktplaats.nl, sport.ro, azet.sk, mundodeportivo.com, dn.se, bluewin.ch, n-tv.de, bergfex.at, dnes.bg, blesk.cz, mtvuutiset.fi, ouest-france.fr, mediaset.it, buienradar.nl, tvn24.pl, google.ru, oe24.at, rtbf.be, dnevno.hr, bt.dk, veikkaus.fi, 3bmeteo.com, irishtimes.com, libertatea.ro, 20minutos.es, sudinfo.be, zamunda.net, centrum.cz, gazeta.pl, hotnews.ro, elpais.com, sinoptik.bg, bazos.cz, seiska.fi, lemonde.fr, gazzetta.it, sport.es, 2dehands.be, novilist.hr, …
> QA cookie banner rules update

- cookie-banner-rules-list.json
I've retained the element dot selector format here from the previous rule, although just using `.a8c-cookie-banner` might be more robust to future changes.
Fixes #19.
> Update gravatar presence selector

- cookie-banner-rules-list.json
Fixing banner flash for the following sites:
offnews.bg, lidl.cz, filmaffinity.com, vrisko.gr, dikaiologitika.gr, fantacalcio.it, voetbal24.be, dagospia.com, independent.co.uk, chip.de, enikos.gr, zalando.ch, lastampa.it, rsvplive.ie.
> QA cookie banner rules fixes

- cookie-banner-rules-list.json
The click rule was too generic causing false-positives.
The updated rule relies on cookie injection rather than clicking. It sets the d_prefs cookie which is a base64 encoded version of the cookie banner preferences.
Fixes #68
> Fix the rule for twitter.com

- cookie-banner-rules-list.json
Merged rule c63efcc1-06e0-42c5-955f-f5a61fd0baa2 (fastly.com, spotify.com) with rule 6c7366a0-4762-47b9-8eeb-04e86cc7a0cc, fixed issue #103 and partly #111.
> Merge various rules

- cookie-banner-rules-list.json
Fixed 14 rules for site breakage - unscrollable content for: wetteronline.de, t-online.de, bloomberg.com, bild.de, focus.de, thesun.ie, thesun.co.uk, oikotie.fi, independent.co.uk, chip.de, gizmodo.com, sky.it, aktuality.sk, azet.sk
> Fixed 14 rules for site breakage - unscrollable content

- cookie-banner-rules-list.json
Merged rules for privacy-mgmt.com, gutekueche.at, businessinsider.com, n-tv.de, bergfex.at, meczyki.pl, newsnow.co.uk, news.sky.com with rule d42bbaee-f96e-47e7-8e81-efc642518e97, added new rules for hs.fi, wetteronline.at, aamulehti.fi, thetimes.co.uk, idealo.de.
> Merge rules using SP iframe

- rs-publish.py
We were always updating records, because RS had extra meta-data fields our repo's records don't include. This should fix the comparison.
Tested on RemoteSettings DEV.
> Sync-script: Fix comparison of repo and remote settings records.

- cookie-banner-rules-list.json
Merged rules for Didomi:
jutarnji.hr, orange.fr, vecernji.hr, sport.es, elespanol.com, in-pocasi.cz, 20minutes.fr, actu.fr, hbvl.be, naszemiasto.pl with rule af4c5b38-d210-472b-9a07-21cbe53c85ab;  krone.at, cas.sk, nova.cz, heureka.sk, free.fr, markiza.sk, willhaben.at, francetvinfo.fr with rule 690aa076-4a8b-48ec-b52c-1443d44ff008; 
Merged rules for OneTrust:
rte.ie with rule 6c7366a0-4762-47b9-8eeb-04e86cc7a0c; tv2.dk with rule 0b42c238-b54d-4106-8d9a-81df5bc0b3ae; glassdoor.com with rule c4b8af6b-5e97-4214-badd-67f716d3e5b6; mailchimp.com with rule a3b0e77d-a7fe-4f38-8015-e368c67ecbbf; coursera.org with rule 8809db65-96cd-4ab5-be1a-cea416a4f34f.
> Merge rules using OneTrust and Didomi CMPs

- cookie-banner-rules-list.json
Merge rules for svd.se, telegraph.co.uk with rule d42bbaee-f96e-47e7-8e81-efc642518e97, fixed issue #104.
> Merge rules for svd.se, telegraph.co.uk

- cookie-banner-rules-list.json
All 45 sites (10+ countries in the GDPR area) share a common cookie rule, based on a single opt-out cookie.  The click rule is also common, having only the opt-in option. Merged rules for  pravda.sk, b92.net, abv.bg, orf.at, expressen.se, nieuwsblad.be, idnes.cz, independent.ie, telegraaf.nl, as.com, njuskalo.hr, slobodnadalmacija.hr, aktualne.cz, dnevnik.hr, nova.bg, mundodeportivo.com, dn.se, blesk.cz, ouest-france.fr, centrum.cz, denik.cz, csfd.cz, standaard.be, heureka.cz, bfmtv.com, filmweb.pl, expresso.pt, lavanguardia.com, idealista.com, idealista.pt, di.se, hola.com, lesoir.be,  vesti.bg, gloria.hr, huffingtonpost.es, rtl.be, hn.cz, gong.bg, okdiario.com, dhnet.be, lecturas.com, hasznaltauto.hu, elperiodico.com, dumpert.nl into rule 77885432-826b-4d03-bb3d-dfdd36015a82.
> Merge rules for sites using Didomi CMP with cookie rules

- cookie-banner-rules-list.json
Merge rules for sites using Didomi CMP
Removed non-functional cookie rules and merged the rules for: leboncoin.fr, rtbf.be, 20minutos.es, sudinfo.be, elpais.com, sinoptik.bg, subito.it, lequipe.fr, abc.es, gva.be, eltiempo.es, eldiario.es, larazon.es, extra.cz, leparisien.fr, ladepeche.fr, marmiton.org, poslovni.hr, reverso.net, softonic.com, sydsvenskan.se, telecinco.es, giphy.com with af4c5b38-d210-472b-9a07-21cbe53c85ab.
> Merge rules for sites using Didomi CMP without cookie rules

- cookie-banner-rules-list.json
Removed click rules, added cookie rules and merged iprima.cz, elmundo.es, marca.com into rule 77885432-826b-4d03-bb3d-dfdd36015a82. Removed rules for libero.it and svd.se for further investigation. For now, these 2 rules cannot be fixed using cookies or CSS selectors. Fixed issues #79, #81, #82, #83, #101, #104.
> Updated rules for unscrollable/banner still present sites

- cookie-banner-rules-list.json
Removed rules for iprima.cz, elmundo.es, marca.com for further investigation. For now, the rule cannot be fixed using cookies or CSS selectors.
> Removed rules for iprima.cz, elmundo.es, marca.com

- cookie-banner-rules-list.json
Added 31 new rules for:
centrum.sk, amazon.se, nlc.hu, aliexpress.ru, search.ch, hrt.hr, ok.ru, jn.pt, arukereso.hu, glasistre.hr, flash.pt, orange.sk, jeuxvideo.com, nzz.ch, echo24.cz, nosalty.hu, ria.com, framar.bg, sverigesradio.se, elisa.fi, dn.no, naslovi.net, dedeman.ro, drei.at, kurir.rs, allocine.fr, komplett.no, proximus.be, chmi.cz, anwb.nl, ansa.it. Removed broken cookie rules for:
mirror.co.uk, alza.cz, femina.hu, poste.it, kauppalehti.fi, news247.gr, alo.bg, borsonline.hu, rabobank.nl, informer.rs, eluniversal.com.mx, athensmagazine.gr, globo.com, express.co.uk, pronews.gr, nettiauto.com, sportdog.gr, emag.hu, ilgiornale.it, tradera.com, alo.rs, mobile.bg, observador.pt, napi.hu, telsu.fi, gossip-tv.gr, vi.nl, news.bg, zougla.gr, calciomercato.com, walmart.ca, newsbeast.gr, …
> Add new rules and update existing rules - 2nd pass through the list (3)

- cookie-banner-rules-list.json
Rules for:
- onetrust
- didomi
- sourcepoint (frame)
These will only apply in Gecko if `cookiebanners.service.enableGlobalRules` is set to `true`.
> Add experimental global rules

- cookie-banner-rules-list.json
Added 48 new rules for:
milenio.com, se.pl, vodafone.pt, mediafax.ro, idealmedia.io, trello.com, zendesk.com, pki.goog, huffpost.com, epicgames.com, theverge.com, onlyfans.com, tandfonline.com, opendns.com, uol.com.br, washington.edu, upwork.com, buzzfeed.com, hugedomains.com, rubiconproject.com, abc.net.au, qualtrics.com, theconversation.com, newyorker.com, jotform.com, apnews.com, mlb.com, ign.com, ea.com, inc.com, apa.org, gamespot.com, pnas.org, hootsuite.com, chicagotribune.com, science.org, xbox.com, gsmarena.com, quillbot.com, politico.com, blackboard.com, ndtv.com, qz.com, roku.com, scmp.com, thetimes.co.uk, braze.com, adjust.com. 
Removed broken cookie rules for: 
telekom.hu, squarespace.com, theatlantic.com, zoho.com, box.com, 9gag.com, mi.com, sciencedaily.com, evernote.com, …
> Add new rules and update existing rules - 2nd pass through the list (4)

- cookie-banner-rules-list.json
Added 21 new rules for:
hln.be, nu.nl, vg.no, aftonbladet.se, ad.nl, finn.no, sporza.be, derstandard.at, tori.fi, vrt.be, spiegel.de, aftenposten.no, vglive.no, klart.se, zeit.de, gala.fr, volkskrant.nl, tek.no, omni.se, dpgmediagroup.com, economist.com
> Added 21 new rules for SP_iframe banners

- cookie-banner-rules-list.json
This is to avoid false positives where we click elements which are unrelated to the cookie banner. 
This also fixes an issue where the Facebook rule only worked on Desktop, not Android.
> Update facebook click rule to be more precise

- cookie-banner-rules-list.json
New CMPs: trustarcbar, quantcast, borlabs, consentmanager.net, cookiebot, complianz
Updated ids for didomi, onetrust, sourcepoint
> Adding (global) CMP rules

- cookie-banner-rules-list.json
`.` in rule ids seems to break the sync script. We only have one rule that uses it so I've updated the ID for now. We should check why exactly this fails and either fix it or update our JSON schema to disallow `.` in id fields.
> Remove dot from rule id fixing RS sync error.

- cookie-banner-rules-list.json
In this pull request, I extended the rule for facebook.com to also apply to oculus.com as per [#199 comment 1](https://github.com/mozilla/cookie-banner-rules-list/pull/199#issuecomment-1570308661).
> Extended the rule for facebook.com to also work on oculus.com

- cookie-banner-rules-list.json
The existing rule responsible for rejecting cookies on the various Stack Exchange websites was not working correctly, so I updated the injected cookie and the date stored in it to one that won't become too old anytime soon. Apart from that, I added an opt-out click rule as a fallback in case this cookie stops working again somewhere in the future.
Also, I added a few other Stack Exchange websites that were missing.
I tested everything gradually, and it worked on my computer, but I'm not sure if it will work for other people as it did for me.
Resolves #41
Fixes #200
> Added new and improved existing rules for Stack Exchange websites

- cookie-banner-rules-list.json
In this pull request, I added a completely new rule to the list for those Valve websites that display a cookie banner (i.e. steamcommunity.com and steampowered.com).
One issue I noticed during testing is that their cookie banner displays with a slight delay, so in some specific cases where the page loads slowly, the banner clicker may time out and miss its chance to close that banner (the default 3000 ms delay is not enough in this case).
On the other hand, it is not that bad since the cookie injector should take care of everything, and clicking will be just a fallback in case Valve messes something up and the cookie stops working correctly.
Resolves #205
> Added a new rule for some Valve websites

- cookie-banner-rules-list.json
https://www.ups.com/ca/en/Home.page
Tested on Firefox 117.0b2
> Add cookie rule for ups.com

- cookie-banner-rules-list.json
The current selectors are too broad as those are about the button styles.
Fixes #214
> Limit theverge.com selectors inside the parent

- cookie-banner-rules-list.json
gmx.net and web.de share a lot of things, including the cookie banner.
> Block cookie banner on gmx.net

- cookie-banner-rules-list.json
- test/validateRules.js
Disabled tumblr.com, paypal.com and Amazon sites. See commit description for details.
> Disabled Tumblr, Paypal, Amazon

- cookie-banner-rules-list.json
This is a rule I initially planned to commit with all the other tech company websites in #333, but it looks like it might be a (heavily modified?) cookie consent manager from some CMP.
The use of the `.cc-window`, `.cc-dismiss`, and `.cc-allow` classes might suggest that this is the Cookie Consent by Insites (https://web.archive.org/web/20190520103530/https://cookieconsent.insites.com/ ), but both the JS code responsible for handling cookies is completely different, and the design of the cookie banner itself also stands out. This can't be it, I think.
For the time being, I propose adding this Dell rule to the list, and perhaps there will be time in the future to further investigate this matter.
Resolves #338
> Added a new rule for Dell websites

- cookie-banner-rules-list.json
In this pull request, I added a new rule for Eclipse websites and websites of Eclipse-affiliated or owned projects that display a cookie banner.
One important note, the cookie banner used by Eclipse on their various websites appears to be some kind of cookie consent manager from some CMP. I presume this is a slightly customized Cookie Consent by Insites (https://web.archive.org/web/20190520103530/https://cookieconsent.insites.com/ ).
I would consider converting this site-specific rule to a global rule, but the use of this CMP by various websites has a few catches, and it won't be as easy as it might seem. Currently, I don't have enough time to get into it.
Resolves #340
> Added a new rule for Eclipse websites

- cookie-banner-rules-list.json
Updated existing site-specific rule to support two Sports Interactive domains.
Fixes #242.
> updated existing rule to support two Sports Interactive domains

- cookie-banner-rules-list.json
Updated existing site-specific rule to support ieee.org and linuxfoundation.eu.
Fixes #63. See #254.
> updated existing rule to support ieee.org and linuxfoundation.eu

- cookie-banner-rules-list.json
Admittedly, the cookie banner that is used on teamspeak.com should be supported after my PR #361 for the ihavecookies CMP is merged, but only partially, as that global rule only supports accepting cookies.
So, for teamspeak.com to be fully supported, something else needs to be done. Unfortunately, in the current implementation of the cookie banner blocker in Firefox, it is not possible to either:
- click multiple times one after the other
- inject cookies in global rules.
Perhaps it will change in the future, but for now, in order to fully support this website, the only solution seems to be to create an almost identical rule to the one I already proposed in the other linked PR, but this time with support for injecting cookies.
Resolves #369
> Added a new rule for teamspeak.com

- cookie-banner-rules-list.json
Updated existing site-specific rule to support france24.com.
Fixes #197.
> updated existing rule to support france24.com

- cookie-banner-rules-list.json
I moved several Stack Exchange domains to a different rule as the previous selector is no longer valid for these domains.
> fixed rule for several Stack Exchange domains

- cookie-banner-rules-list.json
This is a quick update to the existing click rule for asus.com in response to the recent minor cookie banner changes on the Asus side, as described in the linked GitHub issue below.
Fixes #434
> Updated rule for asus.com in response to minor banner changes on the Asus side

- cookie-banner-rules-list.json
Updated existing rule to support Anexia and two more Netcup domains. The domain netcup.com redirects to netcup.eu, but the rule for netcup.com is there to support helpcenter.netcup.com.
> updated existing rule to support Anexia and two more Netcup domains

- cookie-banner-rules-list.json
Added rule for autoscout24.
Fixes #415.
When testing, I noticed that sometimes the banner is not hidden the first time. But after reloading the page, the banner was always hidden in my tests.
> added rule for autoscout24

- cookie-banner-rules-list.json
https://www.lesechos.fr/
https://investir.lesechos.fr/
Tested on Firefox 122.0
> Update existing rule to support lesechos.fr

- cookie-banner-rules-list.json
https://www.radiofrance.fr/
Tested of Firefox 123.0
> Update existing rule to support radiofrance.fr

- cookie-banner-rules-list.json
https://www.but.fr/
Tested on Firefox 123.0
> Add new rule for but.fr

- cookie-banner-rules-list.json
The banner on bloomberg.com has an optOut button that should be used.
Today the banner is not clicked if cookiebanners.service.mode = 1.
https://www.bloomberg.com/
Tested on Firefox 123.0
> Move bloomberg domain to rule with optOut

- cookie-banner-rules-list.json
Adds 2 sites using didomi and move a third one to a rule with an optOut
1. Add https://www.intersport.fr/
2. Add https://www.decathlon.fr/
3. Move https://www.leboncoin.fr/
Tested on Firefox 123.0
> Add didomi sites

- cookie-banner-rules-list.json
In this pull request, I modified the existing rule for silentiumpc.com to add support for krux.tech and spcgear.com, two more domains owned by the same company (Cooling sp. z o.o.).
Resolves #460
> Added support for krux.tech and spcgear.com as well

- cookie-banner-rules-list.json
In this pull request, I separated endorfy.com into its own rule, as it recently started using a different cookie banner, which the current rule was not prepared for. For more information, see the linked GitHub issue below.
Fixes #463
> Re-added support for endorfy.com

- cookie-banner-rules-list.json
* https://www.fnac.com/
* https://www.fnac.pt/
* https://www.nl.fnac.be/
* https://www.fr.fnac.ch/
Tested of Firefox 123.0.1
> Update existing rule to add fnac.com, .be and .pt

- cookie-banner-rules-list.json
In this pull request, I removed the site-specific rule for zyxel.com, as it is now redundant and does not serve its purpose anymore since they started using the CookieScript CMP (for which support has already been proposed by me in another pull request and is waiting for review). See #467 and #356 for more information.
> Removed support for zyxel.com for now due to a banner change to a different one

- cookie-banner-rules-list.json
https://www.gog.com/
Tested of Firefox 123.0.1
> Update rule to add gog.com

- cookie-banner-rules-list.json
This pull request consists of three main parts:
1. A few missing domains from the same owners were added to existing rules
2. One dead link was removed from the Eclipse domain list
3. The list of Verbatim domains was re-examined by me, and it turned out that most of the domains there now redirect to verbatim-europe.com, which... does not have any cookie banner at all (or it is simply not displayed for my location). The only domain for which a redirect has not been added (yet?) is verbatim.co.il. For these reasons, I reduced the list to only one entry. However, I suspect that at some point, the entire rule will have to be thrown away and replaced by a different one.
> Added a few missing domains to existing rules and cleaned up the domain list for Verbatim and Eclipse

- cookie-banner-rules-list.json
1. https://www.fortuneo.fr/
2. https://www.lcl.fr/
Tested on Firefox 123.0.1
> Create new TrustCommander rule for bank sites

- cookie-banner-rules-list.json
In this pull request, I modified the existing rule for the standard cookie banner used by Meta on a large part of their websites to add support for workplace.com. While I’m at it, I also added _partial_ support for meta.com (it only works on some web pages).
Resolves #473
> Added support for workplace.com from Meta

- cookie-banner-rules-list.json
In this pull request, I created a brand new rule for instagram.com to add support for its desktop variant.
The way it works is that it searches for a group of two buttons that are direct siblings and descendants of an element whose role is a dialog. It seems to do the trick.
However, the rule has a few drawbacks:
1. It is based mainly on the position of the various elements in the tree, so any future change by Meta programmers may result in the _accept_ button and not the _reject_ button being selected, which is definitely not what we want. Or alternatively, everything will stop working altogether.
2. Since the new `:has()` pseudo-class is used here, this rule will only work correctly in Firefox 121 and newer, leaving Firefox 120 (where the cookie banner blocker was first enabled by …
> Added support for instagram.com (desktop only)

- cookie-banner-rules-list.json
the cookie injection causes the banner to keep appearing. The click rule still works perfectly and deals with the banner
> Removed cookie injection for politiken.dk

- cookie-banner-rules-list.json
I looked at the most visited sites in France on https://www.similarweb.com/top-websites/france/ and added a few of them and added a few others I came by.
* https://www.rfi.fr/
* https://www.entrepot-du-bricolage.fr/
* https://www.lesnumeriques.com/
* https://www.seloger.com/
* https://www.societe.com/
* https://www.manomano.fr/
* https://www.pagesjaunes.fr/
* https://www.sncf-connect.com/
* https://www.largus.fr/
* https://www.blablacar.fr/
* https://www.bricomarche.com/
* https://www.laposte.fr/
* https://www.laposte.net/accueil
* https://www.urssaf.fr/
* https://www.enedis.fr/
* https://www.mondialrelay.fr/
* https://www.edf.fr/
* https://www.totalenergies.fr/
* https://www.labanquepostale.fr/
* https://www.ldlc.com/
* https://www.ldlc.pro/
* https://www.materiel.net/
* …
> Add a few of the most visited sites in France

- cookie-banner-rules-list.json
`https://www.yazio.com/en`
Tested on Firefox 124.0b9
> Add rule for yazio.com

- cookie-banner-rules-list.json
In this pull request, I propose to add support for the new cookie banner on asus.com (see the linked issue below for a screenshot and more details) by adding a rule for injecting cookies, as the new banner no longer has any cookie reject button to click.
As I said in the linked issue below, I don't know what Asus plans to do next with these banners. Will the new one replace the old one at some point, or maybe Asus will return to the old banner, or maybe everything will remain as it is (because different countries have different rules regarding the protection of personal data).
So for now, while the old banner is still in use, the newly added cookie injection support should handle both the new and old one. The mechanism for clicking the cookie reject button would remain as a fallback for …
> Added support for the new cookie banner on asus.com

- cookie-banner-rules-list.json
`https://gdpr.twitter.com`
Tested on Firefox 125.0b9
Tried to add a rule specific to the subdomain (not sure if it applies to others), but it wouldn't apply due to existing `twitter.com` rule.
> Fix rule for gdpr.twitter.com

- cookie-banner-rules-list.json
Companies usually have different variations of their websites adapted to the characteristics of different markets. Some of them also use different addresses for each one, as Zalando does, for example (which, among others, is part of this PR).
In this pull request, I propose adding support for such localized websites. The full list looks as follows:
- Amazon websites
- BlaBlaCar websites
- CHIP-branded websites
- Crédit Agricole websites
- Decathlon websites
- Ebay websites
- eMAG websites
- Intermarché-branded websites
- INTERSPORT websites
- MediaMarktSaturn websites
- Orange-branded websites
- Pepper platform websites
- Telekom/T-mobile/Magenta-branded websites
- Vodafone websites
- Yandex websites
- Zalando websites
- ZDNET-branded websites
To make the review process easier, I have …
> Added support for localized variations of already supported websites

- cookie-banner-rules-list.json
The CSS classes previously used are not stable, thus switch to a cookie rule.
> Fix rule for galaxus.de

- cookie-banner-rules-list.json
* `https://x.com`
* `https://gdpr.x.com`
Tested on 127.0b4
> Add rule for x.com

- cookie-banner-rules-list.json
In this pull request, I modified the existing rule for the standard cookie banner used by Meta on a large part of their websites to enable automatic handling of this banner by the Firefox cookie banner blocker on some of the meta.com and instagram.com subdomains that use it.
Also, just to make this extra clear and for future reference, I'm adding meta.com and instagram.com to the rule list _not_ to add support for the main banners on both of these websites but to make about.meta.com and about.instagram.com supported respectively (and probably other subdomains I missed).
Resolves #476
Resolves #499
> Added partial support for meta.com and instagram.com

- cookie-banner-rules-list.json
https://www.fandom.com/
This site has a lot of subdomains. A few random examples : 
* https://godzilla.fandom.com
* https://dcextendeduniverse.fandom.com
* https://matrix.fandom.com
> Add optOut in rule for fandom.com

- cookie-banner-rules-list.json
`https://www.thenextweb.com`
Tested on Firefox 122.0b9
> Add rule for thenextweb.com
