mozilla/cookie-banner-rules-list

cookie-banner-rules-list.json

Adding rules for cloudflare.com, google.com.hk, msn.com, yahoo.com, xhamster.com, opera.com, sourceforge.net, digicert.com, webex.com, etsy.com, indeed.com, google.co.in.

QA cookie banner rules updates

---

.dockerignore
rs-publish.py

Fixes https://mozilla-hub.atlassian.net/browse/SE-3339
Bonus: a dockerignore file

Fix rs publish key error

---

.github/workflows/test.yml

Also simplify the config a bit, we don't need to do matrix  testing.

Test CI: Cache npm packages

---

cookie-banner-rules-list.json

Fixing banner flash for the following sites:
20min.ch, aktuality.sk, onet.pl, tv2.dk, idokep.hu, bild.de, 24sata.hr, olx.ro, t-online.de, gsp.ro, ebay.co.uk 
Fixing banner rules not working for the following sites: 
marca.com, repubblica.it

PR #18 Stage verification fixes

---

cookie-banner-rules-list.json

Update yahoo button selectors

---

cookie-banner-rules-list.json

This is essentially the Dutch Amazon.com.

Add rule for bol.com

---

cookie-banner-rules-list.json

Fixing banner flash for the following sites:
corriere.it, olx.bg, olx.pt, heute.at, sportal.bg, sport.ro, azet.sk, bluewin.ch, n-tv.de, mtvuutiset.fi, buienradar.nl, irishtimes.com, libertatea.ro, 20minutos.es, gazeta.pl, hotnews.ro, lemonde.fr, gazzetta.it, 2dehands.be, funda.nl, businessinsider.com.pl, adevarul.ro, rightmove.co.uk, ricardo.ch, viaplay.dk, meteofrance.com, aib.ie, otomoto.pl, mondo.rs, newsit.gr, sport.pl, novini.bg, sport-fm.gr, mirror.co.uk, dhl.de, femina.hu, focus.de, news247.gr, libero.it, medonet.pl, sky.it, fakt.pl, wetteronline.de, athensmagazine.gr, thesun.ie, thesun.co.uk, e-boks.com, voetbalprimeur.nl, oikotie.fi, pronews.gr, ebay.it, ilgiornale.it, tradera.com, amazon.fr, berlingske.dk, newsnow.co.uk, napi.hu, amazon.nl, plejada.pl, gossip-tv.gr, vi.nl, …

PR #21 Stage verification fixes

---

cookie-banner-rules-list.json

This is [the _other_](https://github.com/mozilla/cookie-banner-rules-list/pull/26) Dutch amazon.com.

Add coolblue.nl

---

README.md
cookie-banner-rules-list.json
test/validateRules.js

Migrate to domains field and merge matching rules automatically.
Migration script used: https://github.com/Trikolon/cookie-banner-rules-list-migration/blob/main/migrateDomain.js

Domains field: Migrate and merge

---

cookie-banner-rules-list.json

Changed presence for businessinsider.com.pl - issue #77

Fix the rule for businessinsider.com.pl - #77

---

cookie-banner-rules-list.json

Deleted individual rules for fakt.pl, plejada.pl, medonet.pl and merged them with the rule for onet.pl, changed presence from “div.cmp-app_gdpr” to “div.cmp-popup_popup”.

Merge various rules

---

cookie-banner-rules-list.json

Opting out generates a second banner - removed opt-out element and changed presence - issue #98

Fix the rule for leparisien.fr #98

---

cookie-banner-rules-list.json

Fix the rule for accuweather.com - issue #90.

Fix the rule for accuweather.com #90

---

cookie-banner-rules-list.json

Merge Google rules

---

cookie-banner-rules-list.json

Added rule for autodesk.com

---

cookie-banner-rules-list.json

Updated rule for flickr.com, fixed issues #96, #99, #110.

Updated rule for flickr.com

---

cookie-banner-rules-list.json

Added new rules for canva.com, office.com, adobe.com, zoom.com; added click rule for bing.com, paypal.com; added click rule and removed cookies for yahoo.com; added cookie rule for rule 71443ce9-15b8-4e07-b51b-1f2158521ea9 (askubuntu.com, serverfault.com, stackexchange.com, stackoverflow.com).

Add new rules and update existing rules - 2nd pass through the list

---

cookie-banner-rules-list.json

Disable instagram.com rule on Android.

---

cookie-banner-rules-list.json

add click rule for arte.tv

---

cookie-banner-rules-list.json

Fix YouTube rule #220

---

cookie-banner-rules-list.json

Add netcup and hetzner

---

cookie-banner-rules-list.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1857838

Fixed reload bug with one trust rule

---

cookie-banner-rules-list.json

Fixes #217, #218.
Tested on Firefox 120.0b9.

Add rule for panasonic.com, safeway.com

---

cookie-banner-rules-list.json

Add additional site rules

---

cookie-banner-rules-list.json

Tested in 115.5.0esr and working!

Add rule for zdf.de

---

cookie-banner-rules-list.json

Tested in 115.5.0esr and working!

Add rule for sparda-hessen.de

---

cookie-banner-rules-list.json

Add rule for hdblog.it and hdmotori.it

Add rule for hdblog.it and hdmotori.it

---

cookie-banner-rules-list.json

issue #241 - fixed Shopify rule

---

cookie-banner-rules-list.json

In this pull request, I propose adding support for a bunch of relatively popular tech company websites that, until now, neither had site-specific rules nor were supported by existing global rules.
For a complete and concise list of websites, see the linked GitHub issue at the bottom.
I'm aware that reviewing so many changes in one commit may not be very convenient, but the alternative was to create 15 separate pull requests and merge one after the other, dealing with merge conflicts along the way.
Resolves #332

Added new rules for a bunch of popular tech company websites

---

cookie-banner-rules-list.json

In this pull request, I added a new rule for nazwa.pl. For more information, see the linked GitHub issue below.
Resolves #345

Added a new rule for nazwa.pl

---

cookie-banner-rules-list.json

In this pull request, I added a new rule for action.com, an international chain store operating in Europe, which I came across one day while browsing the Internet.
Resolves #343

Added a new rule for action.com

---

cookie-banner-rules-list.json

issue #248 - added rule for cbinsights.com

---

cookie-banner-rules-list.json

Updated existing site-specific rule to support zdnet.de.
Fixes #247.

updated existing rule to support zdnet.de

---

cookie-banner-rules-list.json

Updated existing site-specific rule to support several OMV domains.
Fixes #105.

updated existing rule to support several OMV domains

---

cookie-banner-rules-list.json

Updated existing site-specific rule to support sparkasse.at.
See #252.

updated existing rule to support sparkasse.at

---

cookie-banner-rules-list.json

Updated existing site-specific rule to support upfit.de.

updated existing rule to support upfit.de

---

cookie-banner-rules-list.json

Added rule for ondo.finance
Fixes #163.

added rule for ondo.finance

---

cookie-banner-rules-list.json

Added rule for androidpolice.com
Fixes #284. Please note https://github.com/mozilla/cookie-banner-rules-list/issues/284#issuecomment-1847820493.

added rule for androidpolice.com

---

cookie-banner-rules-list.json

added more OMV domains

---

cookie-banner-rules-list.json

Updated existing rule to support 3sat.de

updated existing rule to support 3sat.de

---

cookie-banner-rules-list.json

Added rule for hfm-frankfurt.de
Fixes #298.

added rule for hfm-frankfurt.de

---

cookie-banner-rules-list.json

Updated existing rule to support treedom.net.

updated existing rule to support treedom.net

---

cookie-banner-rules-list.json

Updated existing rule to support several Opodo domains.

updated existing rule to support several Opodo domains

---

cookie-banner-rules-list.json

Fixed cookie rule for forbes.com.

fixed cookie rule for forbes.com

---

cookie-banner-rules-list.json

Added rule for comdirect.de
Fixes #419.

added rule for comdirect.de

---

cookie-banner-rules-list.json

added rule for deskmodder.de

---

cookie-banner-rules-list.json

Added rule for dpd.com
Fixes #425.

added rule for dpd.com

---

cookie-banner-rules-list.json

Added rule for stepstone.de
Fixes #414.

added rule for stepstone.de

---

cookie-banner-rules-list.json

Added rule for jw.org
Fixes #409.

added rule for jw.org

---

cookie-banner-rules-list.json

Added rule for gamestar.de.
Fixes #405.

added rule for gamestar.de

---

cookie-banner-rules-list.json

Added rule for 1und1.de.
Fixes #404.

added rule for 1und1.de

---

cookie-banner-rules-list.json

Added rule for kaufmich.com.
Fixes #403.

added rule for kaufmich.com

---

cookie-banner-rules-list.json

Added rule for kicker.de.
Fixes #390.

added rule for kicker.de

---

cookie-banner-rules-list.json

added rule for withings.com

---

cookie-banner-rules-list.json

Create new rule for creditmutuel.fr

---

cookie-banner-rules-list.json

Update rule to add marianne.net

---

cookie-banner-rules-list.json

Create new rule for canalplus.com

---

cookie-banner-rules-list.json

Update rule to add rtl.fr

---

cookie-banner-rules-list.json

Update rule to add tf1info.fr

---

cookie-banner-rules-list.json

Update rule to add pasteur.fr

---

cookie-banner-rules-list.json

Update rule to add darty.com

---

cookie-banner-rules-list.json

In this pull request, I added a new rule specifically for metaconnect.com. For more information, see the linked GitHub issue below.
Resolves #500

Added support for metaconnect.com

---

cookie-banner-rules-list.json

Update rule to add allopneus.com

---

cookie-banner-rules-list.json

* https://www.auto5.be/
* https://www.norauto.es/
* https://www.norauto.fr/
* https://www.norauto.it/
* https://www.norauto.pt/

Update rule to add norauto domains

---

cookie-banner-rules-list.json

Add rule for rp-online.de

---

cookie-banner-rules-list.json

Add rule for duh.de
